source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

use_frameworks!

pod 'Alamofire', :git => "https://github.com/Alamofire/Alamofire.git"
pod 'SwiftyJSON', :git => "https://github.com/SwiftyJSON/SwiftyJSON.git"
pod 'Snap', :git => "https://github.com/Masonry/Snap.git"
pod 'Haneke', :git => "https://github.com/Haneke/Haneke.git"
pod 'AFNetworking', :git => "https://github.com/AFNetworking/AFNetworking.git"
pod 'BDBOAuth1Manager', :git => "https://github.com/bdbergeron/BDBOAuth1Manager.git"